name: Train TuneAi SLM
on: [workflow_dispatch, push]

jobs:
  train-model:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory:./TuneAI

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: pip install torch numpy tqdm

      - name: Run Pipeline
        run: |
          python data_prepare.py
          python train.py

      - name: Upload Trained Brain
        uses: actions/upload-artifact@v4
        with:
          name: TuneAi-Weights
          path: TuneAI/checkpoints/tuneai_v1.pth
